"""add full_name and email to user

Revision ID: 2746a40eacf1
Revises: 74af4e949b0b
Create Date: 2026-02-17 22:00:04.209434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2746a40eacf1'
down_revision = '74af4e949b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
